/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author nrochas
 */
public class FenAccueil extends FrameGenerik {

    /**
     * Creates new form FenAccueil
     */
    public FenAccueil()
        {
        
        initComponents();
        this.getContentPane().setBackground(params.ColorChart.colorBack);
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labTitre = new javax.swing.JLabel();
        panelButton = new javax.swing.JPanel();
        butBatchL = new ButtonGenerik();
        butSettings = new ButtonGenerik();
        butScreen = new ButtonGenerik();
        butModeEmploi = new ButtonGenerik();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Accueil");

        labTitre.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        labTitre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labTitre.setText("Automate d'Aide au Parametrage");

        panelButton.setOpaque(false);

        butBatchL.setText("Aide BatchLangue");
        butBatchL.setEnabled(false);
        butBatchL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butBatchLActionPerformed(evt);
            }
        });

        butSettings.setText("Settings");
        butSettings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butSettingsActionPerformed(evt);
            }
        });

        butScreen.setText("Aide Screenshot");
        butScreen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butScreenActionPerformed(evt);
            }
        });

        butModeEmploi.setText("Mode d'Emploi");
        butModeEmploi.setToolTipText("");
        butModeEmploi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butModeEmploiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelButtonLayout = new javax.swing.GroupLayout(panelButton);
        panelButton.setLayout(panelButtonLayout);
        panelButtonLayout.setHorizontalGroup(
            panelButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelButtonLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(butScreen, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(butBatchL, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(butSettings, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(butModeEmploi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelButtonLayout.setVerticalGroup(
            panelButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelButtonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(butScreen)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(butBatchL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(butSettings)
                .addGap(18, 18, 18)
                .addComponent(butModeEmploi)
                .addContainerGap(112, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labTitre, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 407, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(130, 130, 130))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(labTitre, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panelButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void butScreenActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_butScreenActionPerformed
    {//GEN-HEADEREND:event_butScreenActionPerformed
        Fenetre f = new Fenetre();
                f.setLocation(500, 200);
                f.setSize(850, 400);
                
                f.setVisible(true);
                this.setVisible(false);
    }//GEN-LAST:event_butScreenActionPerformed

    private void butBatchLActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_butBatchLActionPerformed
    {//GEN-HEADEREND:event_butBatchLActionPerformed
       FenBatchLangue f = new FenBatchLangue();
        f.setLocation(500, 200);
                f.setSize(850, 400);
                f.setVisible(true);
                this.dispose();
       
    }//GEN-LAST:event_butBatchLActionPerformed

    private void butModeEmploiActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_butModeEmploiActionPerformed
    {//GEN-HEADEREND:event_butModeEmploiActionPerformed
      
        FenModeEmploi fme = new FenModeEmploi();
       fme.setLocation(500, 200);
                fme.setSize(850, 400);
                fme.setVisible(true);
       
    }//GEN-LAST:event_butModeEmploiActionPerformed

    private void butSettingsActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_butSettingsActionPerformed
    {//GEN-HEADEREND:event_butSettingsActionPerformed
        FenSettings fs = new FenSettings();
       fs.setLocation(500, 200);
                fs.setSize(850, 400);
                fs.setVisible(true);
       
    }//GEN-LAST:event_butSettingsActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butBatchL;
    private javax.swing.JButton butModeEmploi;
    private javax.swing.JButton butScreen;
    private javax.swing.JButton butSettings;
    private javax.swing.JLabel labTitre;
    private javax.swing.JPanel panelButton;
    // End of variables declaration//GEN-END:variables
}
