/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import automate.EcrivainBatchLang;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.ERROR_MESSAGE;

/**
 *
 * @author nrochas
 */
public class FenBatchLangue extends FrameGenerik {

   
    
    public FenBatchLangue()
        {
        ecrBL = new EcrivainBatchLang();
        initComponents();
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        labTitre = new javax.swing.JLabel();
        butGenere = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labTitre.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        labTitre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labTitre.setText("Aide pour Batch de Langue");

        butGenere.setText("Generer Batch Langue");
        butGenere.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                butGenereActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labTitre, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addComponent(butGenere)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(labTitre, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 174, Short.MAX_VALUE)
                .addComponent(butGenere)
                .addGap(65, 65, 65))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void butGenereActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_butGenereActionPerformed
    {//GEN-HEADEREND:event_butGenereActionPerformed
        boolean bob;
        ArrayList<String> testL = new ArrayList<>();
        testL.add("AU_AU");
        ArrayList<String> testM = new ArrayList<>();
        testM.add("FACTQI");
    bob =ecrBL.editBatch("CZPLtest", "9", "v9.0","2.8", "1.6.5", "99879", testL, testM, "T9xI99");
    
    if (bob)
    {JOptionPane.showMessageDialog(this, "Batch créé");
    this.dispose();}
      
    }//GEN-LAST:event_butGenereActionPerformed

    private EcrivainBatchLang ecrBL;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butGenere;
    private javax.swing.JLabel labTitre;
    // End of variables declaration//GEN-END:variables
}
