/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import Outils.ToolsString;
import Outils.XmlTools;
import entity.Formulaire;
import entity.Methode;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.ERROR_MESSAGE;
import params.Params;

/**
 *
 * @author nrochas
 */
public class FenManualSelect extends javax.swing.JFrame {

    /**
     * Creates new form ManualSelect
     */
    public FenManualSelect()
        {
            list = Formulaire.getInstance().getListFormulaire();
            cible = Methode.getInstance().getListFDEF().toString();
        initComponents();
        }

    public FenManualSelect(ArrayList<String> li, String str)
        {
        list = li;
        cible = str;
        initComponents();

        }
 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jScrollPane1 = new javax.swing.JScrollPane();
        listdeFDEF = new javax.swing.JList<>();
        titreCible = new javax.swing.JLabel();
        labCible = new javax.swing.JLabel();
        titre = new javax.swing.JLabel();
        butLancez = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Selection Manuelle");
        setAlwaysOnTop(true);
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setModalExclusionType(java.awt.Dialog.ModalExclusionType.APPLICATION_EXCLUDE);
        setType(java.awt.Window.Type.UTILITY);

        listdeFDEF.setModel(new modele.ListModelFormulaire());
        listdeFDEF.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(listdeFDEF);

        titreCible.setText("Choisissez la FDEF correspondante à:");

        labCible.setText(cible);

        titre.setText("Ambiguité dans les ID. Selectionner le FDEF manuellement");

        butLancez.setText("Validez");
        butLancez.setToolTipText("");
        butLancez.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                butLancezActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(titre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(titreCible, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(103, 103, 103))
                            .addComponent(labCible, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(butLancez))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(titre, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(titreCible, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labCible, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(79, 79, 79)
                        .addComponent(butLancez))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void butLancezActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_butLancezActionPerformed
    {//GEN-HEADEREND:event_butLancezActionPerformed
        String selection = listdeFDEF.getSelectedValue();
        if (selection!= null && !selection.trim().equals("")) {
            //ToolsString.setResultat(selection);
            XmlTools.addToParams(Params.docParams, cible, selection);
        }
        else
        {
              JOptionPane.showMessageDialog(this, "Selectionnez un item!", "error", ERROR_MESSAGE);
        }
        this.dispose();

    }//GEN-LAST:event_butLancezActionPerformed

    private String cible;
    private ArrayList<String> list = new ArrayList();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butLancez;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labCible;
    private javax.swing.JList<String> listdeFDEF;
    private javax.swing.JLabel titre;
    private javax.swing.JLabel titreCible;
    // End of variables declaration//GEN-END:variables
}
