/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author nik
 */
public class PanelACopier extends FrameGenerik
{

    /**
     * Creates new form PanelACopier
     */
     public PanelACopier()
    {
        initComponents();
      
    }
    public PanelACopier(String script)
    {
        initComponents();
        txtACopier.setText(script);       
    }
 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        titreaCopier = new javax.swing.JLabel();
        textACopier = new javax.swing.JScrollPane();
        txtACopier = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        titreaCopier.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        titreaCopier.setText("CopiColler le texte ci dessous");

        textACopier.setViewportView(txtACopier);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(titreaCopier, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(597, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(textACopier)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titreaCopier)
                .addGap(18, 18, 18)
                .addComponent(textACopier, javax.swing.GroupLayout.PREFERRED_SIZE, 423, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(52, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane textACopier;
    private javax.swing.JLabel titreaCopier;
    private javax.swing.JTextPane txtACopier;
    // End of variables declaration//GEN-END:variables
}
